# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://plotti.co
title: Plottico Beta
email: ag@plotti.co
author: Plottico
description: > # "Write an awesome description for your new site here. 
  Announcing private beta for Plottico Tracker - your personal zero-effort dynamic data extraction.
copyright: 'Copyright &copy; 2016 Plottico Inc. All Rights Reserved.'
credits: 'Plottico is a beta quality product and comes with no warranty. For more information please send your requests to <a href="mailto:info@vrayo.com">ag@plotti.co</a> or call +1(650)388-9499'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/plottico
  - title: github
    url: https://github.com/grandrew/plotti.co
  - title: linkedin
    url: https://www.linkedin.com/in/grandrew
